name = "Chocolate Minecraft"
author = "zurgeg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba0ab9c2dc49269f767a2ecd0ae1b33bdd22306553563986587349f1d41c86e3"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
