name = "Chocolate Minecraft"
author = "zurgeg"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a987ec307b9061c03ef3c1eb17d1fc6464de2faf60d6d6682ba27558b706b60"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
