name = "Chocolate Minecraft"
author = "zurgeg"
version = "3.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "538ff31183d8d622aee78b7d675dcb3872a1681b1b60d3708d6597968f0e2c54"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
